'use client';

import { useState } from 'react';
import { format } from 'date-fns';
import { Assignment } from '@/types';

interface StudentInfo {
  name: string;
  rollNumber: string;
  section: string;
}

const difficultyLabel: Record<string, string> = {
  easy: 'Easy',
  medium: 'Moderate',
  hard: 'Hard',
};

const difficultyClass: Record<string, string> = {
  easy: 'badge-easy',
  medium: 'badge-medium',
  hard: 'badge-hard',
};

const difficultyDot: Record<string, string> = {
  easy: 'var(--emerald)',
  medium: 'var(--gold)',
  hard: 'var(--crimson)',
};

const sectionLetters = ['A', 'B', 'C', 'D', 'E', 'F'];

export default function QuestionPaper({ assignment }: { assignment: Assignment }) {
  const [student, setStudent] = useState<StudentInfo>({ name: '', rollNumber: '', section: '' });

  if (!assignment.result) return null;

  const { sections, metadata } = assignment.result;

  return (
    <div className="animate-fade-up">
      <div
        className="card overflow-hidden mb-6 no-print"
        style={{ background: 'linear-gradient(135deg, #1a1510 0%, #2d261e 100%)' }}
      >
        <div className="p-6 flex items-center justify-between">
          <div>
            <p className="text-xs mb-1" style={{ color: 'rgba(255,255,255,0.5)' }}>Generated Successfully</p>
            <h2 className="serif text-white text-xl">{assignment.title}</h2>
            <p className="text-sm mt-1" style={{ color: 'rgba(255,255,255,0.6)' }}>
              {assignment.subject} · {metadata.totalQuestions} questions · {metadata.totalMarks} marks
            </p>
          </div>
          <div className="text-right">
            <div
              className="text-3xl font-bold serif"
              style={{ color: 'var(--gold-light)' }}
            >
              {metadata.totalMarks}
            </div>
            <div className="text-xs" style={{ color: 'rgba(255,255,255,0.4)' }}>Total Marks</div>
          </div>
        </div>
        <div className="flex gap-4 px-6 pb-5">
          {sections.map((s, i) => (
            <div key={i} className="flex items-center gap-1.5">
              <div
                className="w-5 h-5 rounded-md flex items-center justify-center text-xs font-bold"
                style={{ background: 'rgba(255,255,255,0.1)', color: 'var(--gold-light)' }}
              >
                {sectionLetters[i]}
              </div>
              <span className="text-xs" style={{ color: 'rgba(255,255,255,0.5)' }}>
                {s.questions.length}Q · {s.totalMarks}M
              </span>
            </div>
          ))}
        </div>
      </div>

      <div
        id="question-paper"
        className="card overflow-hidden"
        style={{ fontFamily: "'DM Sans', sans-serif" }}
      >
        <div
          className="px-10 py-8 border-b"
          style={{ background: 'var(--ink)', borderColor: 'rgba(255,255,255,0.08)' }}
        >
          <div className="text-center mb-6">
            <p className="text-xs uppercase tracking-widest mb-2" style={{ color: 'rgba(255,255,255,0.4)' }}>
              Generated by VedaAI
            </p>
            <h1 className="serif text-white text-2xl md:text-3xl mb-1">{assignment.title}</h1>
            <p className="text-sm" style={{ color: 'rgba(255,255,255,0.6)' }}>
              Subject: {assignment.subject}
            </p>
          </div>

          <div className="flex flex-wrap items-center justify-between gap-4 pt-5 border-t" style={{ borderColor: 'rgba(255,255,255,0.1)' }}>
            <div className="flex gap-6 text-sm">
              <div>
                <span style={{ color: 'rgba(255,255,255,0.4)' }}>Total Marks: </span>
                <span className="font-semibold text-white">{metadata.totalMarks}</span>
              </div>
              <div>
                <span style={{ color: 'rgba(255,255,255,0.4)' }}>Questions: </span>
                <span className="font-semibold text-white">{metadata.totalQuestions}</span>
              </div>
              <div>
                <span style={{ color: 'rgba(255,255,255,0.4)' }}>Due: </span>
                <span className="font-semibold text-white">
                  {format(new Date(assignment.dueDate), 'dd MMM yyyy')}
                </span>
              </div>
            </div>
            <div>
              <span className="text-xs" style={{ color: 'rgba(255,255,255,0.4)' }}>
                Difficulty: <span className="capitalize text-white">{assignment.difficulty}</span>
              </span>
            </div>
          </div>
        </div>

        <div className="px-10 py-6 border-b" style={{ borderColor: 'var(--border)', background: 'var(--parchment)' }}>
          <h3 className="text-xs uppercase tracking-widest mb-4 font-semibold" style={{ color: 'var(--ink-light)' }}>
            Student Details
          </h3>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-5">
            {[
              { label: 'Student Name', key: 'name', placeholder: 'Full name' },
              { label: 'Roll Number', key: 'rollNumber', placeholder: 'Roll / Reg. no.' },
              { label: 'Section', key: 'section', placeholder: 'Section / Class' },
            ].map(({ label, key, placeholder }) => (
              <div key={key}>
                <label className="label text-xs">{label}</label>
                <input
                  type="text"
                  value={student[key as keyof StudentInfo]}
                  onChange={(e) => setStudent((prev) => ({ ...prev, [key]: e.target.value }))}
                  placeholder={placeholder}
                  className="input-field text-sm"
                />
              </div>
            ))}
          </div>
        </div>

        <div className="px-10 py-8">
          {sections.map((section, sIdx) => {
            const letter = sectionLetters[sIdx] || String(sIdx + 1);
            let qCounter = sections.slice(0, sIdx).reduce((acc, s) => acc + s.questions.length, 0);

            return (
              <div key={sIdx} className={sIdx > 0 ? 'mt-10 pt-8 border-t' : ''} style={{ borderColor: 'var(--border)' }}>
                <div className="flex items-start justify-between mb-2">
                  <div className="flex items-center gap-3">
                    <div
                      className="w-9 h-9 rounded-xl flex items-center justify-center font-bold text-sm serif flex-shrink-0"
                      style={{ background: 'var(--ink)', color: 'var(--gold-light)' }}
                    >
                      {letter}
                    </div>
                    <div>
                      <h2 className="serif text-ink text-lg font-semibold">Section {letter}</h2>
                      <p className="text-xs italic" style={{ color: 'var(--ink-muted)' }}>
                        {section.instruction}
                      </p>
                    </div>
                  </div>
                  <div className="text-right flex-shrink-0 ml-4">
                    <span className="text-xs font-semibold" style={{ color: 'var(--ink-light)' }}>
                      {section.questions.length} questions · {section.totalMarks} marks
                    </span>
                  </div>
                </div>

                <div className="mt-5 space-y-4">
                  {section.questions.map((q, qIdx) => {
                    qCounter++;
                    return (
                      <div
                        key={qIdx}
                        className="flex gap-4 p-4 rounded-xl transition-colors"
                        style={{ background: qIdx % 2 === 0 ? 'var(--parchment)' : 'white' }}
                      >
                        <div
                          className="w-7 h-7 rounded-lg flex items-center justify-center text-xs font-bold flex-shrink-0 mt-0.5 mono"
                          style={{ background: 'var(--parchment-dark)', color: 'var(--ink-muted)' }}
                        >
                          {qCounter}
                        </div>
                        <div className="flex-1 min-w-0">
                          <p className="text-sm text-ink leading-relaxed">{q.text}</p>
                          {(q.type === 'long-answer' || q.type === 'short-answer') && (
                            <div
                              className="mt-3 rounded-lg border border-dashed"
                              style={{
                                borderColor: 'var(--border)',
                                height: q.type === 'long-answer' ? '80px' : '40px',
                              }}
                            />
                          )}
                        </div>
                        <div className="flex flex-col items-end gap-2 flex-shrink-0 ml-2">
                          <span
                            className="text-xs font-semibold px-2 py-1 rounded-lg"
                            style={{ background: 'var(--ink)', color: 'var(--gold-light)' }}
                          >
                            {q.marks}M
                          </span>
                          <span className={difficultyClass[q.difficulty] || 'badge-medium'}>
                            <span
                              className="w-1.5 h-1.5 rounded-full"
                              style={{ background: difficultyDot[q.difficulty] || 'var(--gold)', display: 'inline-block' }}
                            />
                            {difficultyLabel[q.difficulty] || q.difficulty}
                          </span>
                        </div>
                      </div>
                    );
                  })}
                </div>
              </div>
            );
          })}

          <div
            className="mt-10 pt-6 border-t text-center"
            style={{ borderColor: 'var(--border)' }}
          >
            <p className="text-xs italic" style={{ color: 'var(--ink-light)' }}>
              *** End of Question Paper ***
            </p>
            <p className="text-xs mt-2" style={{ color: 'var(--ink-light)' }}>
              Generated on {format(new Date(metadata.generatedAt), 'dd MMM yyyy, hh:mm a')} · VedaAI Assessment Creator
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
